README.md
project/plugins.sbt

The change also bumps the sbt-nexus dependency to 0.3.11.
Fixes #1

Added README badges for gitter, job status and release

---

modules/service-commons/src/main/scala/ch/epfl/bluebrain/nexus/service/commons/persistence/SequentialTagIndexer.scala
modules/service-commons/src/test/scala/ch/epfl/bluebrain/nexus/service/commons/persistence/SequentialTagIndexerSpec.scala

Offers the possibility to pass an init function to the indexers, which will be executed
during the preStart f the Cluster Singleton Actor on the index.

Added init function to Indexers

---

.scalafmt.conf
build.sbt
modules/service/src/main/resources/kamon.conf

Added kamon.conf to the service commons

---

modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/IamClient.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/acls/AccessControlList.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/identity/Caller.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/IamClientSpec.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/acls/AccessControlListSpec.scala

Added a method to fetch the collapsed permissions from ACLs

Decoupled IamClient with Caller and use OAuth2BearerToken instead

---

build.sbt
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/acls/Event.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/auth/User.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/auth/UserInfo.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/identity/Caller.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/identity/Identity.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/identity/IdentityId.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/io/serialization/EventJsonLdSerialization.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/IamClientSpec.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/acls/AccessControlListSpec.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/auth/UserInfoSpec.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/auth/UserSpec.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/identity/IdentitySpec.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/io/serialization/EventJsonLdSerializationSpec.scala

Added an id on the Identity data type which represents the unique id of that identity

Added JSON-LD serialization of IAM Events

---

modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/IamClient.scala
modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/identity/Caller.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/IamClientSpec.scala

It allows you to set up different Anonymous Identities,
one with unqualified id and one with qualified id

Added a custom Anonymous Identity to the AnonymousCaller

---

modules/iam/src/main/scala/ch/epfl/bluebrain/nexus/commons/iam/IamClient.scala
modules/iam/src/test/scala/ch/epfl/bluebrain/nexus/commons/iam/IamClientSpec.scala

Add filterGroups parameter to IAM client.

---

build.sbt
modules/http/src/main/scala/ch/epfl/bluebrain/nexus/commons/http/JsonLdCirceSupport.scala
modules/http/src/main/scala/ch/epfl/bluebrain/nexus/commons/http/RdfMediaTypes.scala
modules/http/src/test/resources/iam_json/acls.json
modules/http/src/test/resources/iam_json/acls_ordered.json
modules/http/src/test/resources/iam_json/user.json
modules/http/src/test/resources/iam_json/user_ordered.json
modules/http/src/test/resources/kg_json/activity_instance.json
modules/http/src/test/resources/kg_json/activity_instance_att.json
modules/http/src/test/resources/kg_json/activity_instance_att_ordered.json
modules/http/src/test/resources/kg_json/activity_instance_ordered.json
modules/http/src/test/resources/kg_json/activity_schema.json
modules/http/src/test/resources/kg_json/activity_schema_ordered.json
modules/http/src/test/scala/ch/epfl/bluebrain/nexus/commons/http/JsonLdCirceSupportSpec.scala
modules/ld/sparql-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/SparqlCirceSupport.scala
modules/ld/sparql-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/SparqlClient.scala

Sorted JSON-LD response with the provided OrderedKeys

---

build.sbt
modules/http/src/main/scala/ch/epfl/bluebrain/nexus/commons/http/JsonLdCirceSupport.scala
modules/http/src/test/resources/kg_json/kg_fake_schema.json
modules/http/src/test/scala/ch/epfl/bluebrain/nexus/commons/http/JsonLdCirceSupportSpec.scala

Added a marshaller for A => HTTP entity using JSON-LD

---

modules/schemas/src/main/resources/contexts/nexus/core/links/v0.1.0.json
modules/schemas/src/main/resources/contexts/nexus/core/search/v0.1.0.json

Added context for search to commons-schemas

---

modules/schemas/src/main/resources/contexts/nexus/core/distribution/v0.1.0.json

Mapped value prefix name to schema/value in the distribution context

---

modules/schemas/src/main/resources/contexts/nexus/core/shacl20170720/v0.1.0.json

Added pattern prefix mapping in the shacl context

---

modules/schemas/src/main/resources/contexts/nexus/core/shacl20170720/v0.1.0.json

Remove @list container in path, and, or, xone mappings in the SHACL context

---

modules/schemas/src/main/resources/contexts/nexus/core/search/v0.1.0.json

Force path field to be an id

---

modules/schemas/src/main/resources/contexts/nexus/core/resource/v0.2.0.json
modules/schemas/src/main/resources/contexts/nexus/core/resource/v0.3.0.json

Added a prefix mapping for nxv

---

build.sbt
modules/elastic-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticClientSpec.scala
modules/http/src/test/scala/ch/epfl/bluebrain/nexus/commons/http/HttpClientSpec.scala
modules/sparql-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/SparqlClientSpec.scala

And increase some timeouts in tests.

Fix publishsettings

---

modules/schemas/src/main/resources/contexts/nexus/core/error/v0.1.0.json

Used @id instead of @code in the code prefix mapping

---

build.sbt
modules/ld/shacl-topquadrant-validator/src/main/resources/shacl-context-resp.json
modules/ld/shacl-topquadrant-validator/src/main/resources/shacl-shacl.ttl
modules/ld/shacl-topquadrant-validator/src/main/scala/ch/epfl/bluebrain/nexus/commons/shacl/topquadrant/ShaclEngine.scala
modules/ld/shacl-topquadrant-validator/src/main/scala/ch/epfl/bluebrain/nexus/commons/shacl/topquadrant/ValidationReport.scala
modules/ld/shacl-topquadrant-validator/src/main/scala/ch/epfl/bluebrain/nexus/commons/shacl/topquadrant/Vocabulary.scala
modules/ld/shacl-topquadrant-validator/src/test/resources/conforms.json
modules/ld/shacl-topquadrant-validator/src/test/resources/failed.json
modules/ld/shacl-topquadrant-validator/src/test/scala/ch/epfl/bluebrain/nexus/commons/shacl/topquadrant/ValidationReportSpec.scala
project/build.properties
project/plugins.sbt

Added top quadrant validator

---

build.sbt
modules/elastic-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticSearchBaseClient.scala
modules/elastic-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticSearchClient.scala
modules/elastic-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticSearchDecoder.scala
modules/elastic-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticSearchFailure.scala
modules/elastic-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticSearchQueryClient.scala
modules/elastic-client/src/test/resources/resource.json
modules/elastic-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/es/client/BulkInsertBenchmark.scala
modules/elastic-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticSearchClientSpec.scala
modules/elastic-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/es/client/ElasticSearchDecoderSpec.scala
modules/sparql-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/HttpSparqlClient.scala
modules/sparql-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/SparqlClient.scala
modules/sparql-client/src/main/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/SparqlWriteQuery.scala
modules/sparql-client/src/test/resources/logback-test.xml
modules/sparql-client/src/test/resources/resource.json
modules/sparql-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/BlazegraphClientFixture.scala
modules/sparql-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/BlazegraphClientSpec.scala
modules/sparql-client/src/test/scala/ch/epfl/bluebrain/nexus/commons/sparql/client/BulkInsertBenchmark.scala
project/plugins.sbt

Also added benchmarking for ElasticSearch and Blazegraph bulk operations with different bulk sizes.

Added bulk insert support into SparqlClient

---

Jenkinsfile
build.sbt
modules/akka-downing/src/main/resources/reference.conf
modules/akka-downing/src/main/scala/ch/epfl/bluebrain/nexus/commons/downing/KeepOldestAkkaDowningProvider.scala
modules/akka-downing/src/main/scala/ch/epfl/bluebrain/nexus/commons/downing/config/Settings.scala
modules/akka-downing/src/multi-jvm/resources/config.conf
modules/akka-downing/src/multi-jvm/scala/ch/epfl/bluebrain/nexus/commons/downing/DowningConfig.scala
modules/akka-downing/src/multi-jvm/scala/ch/epfl/bluebrain/nexus/commons/downing/KeepOldestSpec.scala
modules/akka-downing/src/multi-jvm/scala/ch/epfl/bluebrain/nexus/commons/downing/MultiNodeClusterSpec.scala
project/plugins.sbt

Downing implementation using keepOldest strategy inspired on [Akka Split Brain Resolver](https://doc.akka.io/docs/akka-enhancements/current/split-brain-resolver.html)

Implemented Akka Cluster downing using keepOldest strategy

---

modules/core/src/main/scala/ch/epfl/bluebrain/nexus/commons/shacl/ShaclEngine.scala
modules/core/src/main/scala/ch/epfl/bluebrain/nexus/commons/shacl/ValidationReport.scala
modules/core/src/test/scala/ch/epfl/bluebrain/nexus/commons/shacl/ValidationReportSpec.scala

Returned Either instead of Option for **ShaclEngine** for better logging and error handling

Returned Either instead of Option for ShaclEngine
